spring:
  application:
    name: notification-service
  config:
    #    import: configserver:http://config-service:8001
    import: configserver:http://localhost:8001
  cloud:
    config:
      fail-fast: true
      password: admin
      username: user