--liquibase formatted sql

--changeset faspix:1
CREATE TABLE IF NOT EXISTS bill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    is_default BOOLEAN NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    overdraft_enabled BOOLEAN NOT NULL
);
