--liquibase formatted sql

--changeset faspix:1
CREATE TABLE IF NOT EXISTS deposit (
    deposit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(19,2) NOT NULL,
    bill_id BIGINT NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    email VARCHAR(255) NOT NULL
);
