spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
        git:
          uri: https://github.com/faspix/spring-cloud-microservices-config.git
          clone-on-start: true
          basedir: c:/tmp/git-spring-cloud-microservices-config
          default-label: main
  profiles:
    active: git
  security:
    user:
      password: admin

server:
  port: 8001